spring:
  profiles:
    datasource:
      url: jdbc:mysql://localhost:3306/ebook_chat
      username: root
      password: root
      testWhileIdle: true
      validationQuery: SELECT 1
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    session:
      store-type: redis
      thymeleaf:
        cache: false
      messages:
        cache-seconds: 0
      redis:
        host: localhost
        port: 6379
      data:
        redis:
          repositories:
            enabled: true

flyway.enable: true
security.headers.cache: false
server.session.timeout: 600

ebook:
  chat:
    relay:
      host: localhost
      port: 61613